import * as $rdf from "rdflib";

export const ns = {
    LDP: $rdf.Namespace('http://www.w3.org/ns/ldp#'),
    FOAF: $rdf.Namespace('http://xmlns.com/foaf/0.1/'),
    XSD: $rdf.Namespace('http://www.w3.org/2001/XMLSchema#'),
    RDF: $rdf.Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#'),
    RDFS: $rdf.Namespace('http://www.w3.org/2000/01/rdf-schema#'),
    SCHEMA: $rdf.Namespace('http://schema.org/'),
    SOLID: $rdf.Namespace('http://www.w3.org/ns/solid/terms#'),
    VCARD: $rdf.Namespace('http://www.w3.org/2006/vcard/ns#'),
    ORG: $rdf.Namespace('http://www.w3.org/ns/org#'),
    PIM: $rdf.Namespace('http://www.w3.org/ns/pim/space#'),
    NEO: $rdf.Namespace('https://neo.graphmetrix.net/node/'),
    TAG: $rdf.Namespace('http://www.holygoat.co.uk/owl/redwood/0.1/tags/'),
    DCTERMS: $rdf.Namespace("http://purl.org/dc/terms/"),
    ACL: $rdf.Namespace('http://www.w3.org/ns/auth/acl#'),
    ACP: $rdf.Namespace('http://www.w3.org/ns/solid/acp#'),
    sio: $rdf.Namespace('http://semanticscience.org/resource/'),
    GMXO: $rdf.Namespace('https://ontology.graphmetrix.com/node/'),
    EVENT: $rdf.Namespace('http://purl.org/NET/c4dm/event.owl#'),
    OPMV:  $rdf.Namespace('http://purl.org/net/opmv/ns#'),
    PROV: $rdf.Namespace('http://www.w3.org/ns/prov#'),
    URI4URI: $rdf.Namespace('http://uri4uri.net/vocab#'),
    POSIX: $rdf.Namespace('https://www.w3.org/ns/posix/stat#'),
    TL: $rdf.Namespace('http://purl.org/NET/c4dm/timeline.owl#'),
    GEO: $rdf.Namespace('http://www.w3.org/2003/01/geo/wgs84_pos#'),
};


export const nu = {
    LDP: 'http://www.w3.org/ns/ldp#',
    FOAF: 'http://xmlns.com/foaf/0.1/',
    XSD: 'http://www.w3.org/2001/XMLSchema#',
    RDF: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    RDFS: 'http://www.w3.org/2000/01/rdf-schema#',
    SCHEMA: 'http://schema.org/',
    SOLID: 'http://www.w3.org/ns/solid/terms#',
    VCARD: 'http://www.w3.org/2006/vcard/ns#',
    ORG: 'http://www.w3.org/ns/org#',
    PIM: 'http://www.w3.org/ns/pim/space#',
    NEO: 'https://neo.graphmetrix.net/node/',
    TAG: 'http://www.holygoat.co.uk/owl/redwood/0.1/tags/',
    DCTERMS: "http://purl.org/dc/terms/",
    ACL: 'http://www.w3.org/ns/auth/acl#',
    ACP: 'http://www.w3.org/ns/solid/acp#',
    SIO: 'http://semanticscience.org/resource/',
    GMXO: 'https://ontology.graphmetrix.com/node/',
    EVENT: 'http://purl.org/NET/c4dm/event.owl#',
    OPMV: 'http://purl.org/net/opmv/ns#',
    PROV: 'http://www.w3.org/ns/prov#',
    URI4URI: 'http://uri4uri.net/vocab#',
    POSIX: 'https://www.w3.org/ns/posix/stat#',
    TL: 'http://purl.org/NET/c4dm/timeline.owl#',
    GEO: 'http://www.w3.org/2003/01/geo/wgs84_pos#',
};

export const prefixes: Record<string, string> = {
    ldp: 'http://www.w3.org/ns/ldp#',
    foaf: 'http://xmlns.com/foaf/0.1/',
    xsd: 'http://www.w3.org/2001/XMLSchema#',
    rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
    schema: 'http://schema.org/',
    solid: 'http://www.w3.org/ns/solid/terms#',
    vcard: 'http://www.w3.org/2006/vcard/ns#',
    org: 'http://www.w3.org/ns/org#',
    pim: 'http://www.w3.org/ns/pim/space#',
    neo: 'https://neo.graphmetrix.net/node/',
    tag: 'http://www.holygoat.co.uk/owl/redwood/0.1/tags/',
    dcterms: "http://purl.org/dc/terms/",
    acl: 'http://www.w3.org/ns/auth/acl#',
    acp: 'http://www.w3.org/ns/solid/acp#',
    sio: 'http://semanticscience.org/resource/',
    gmxo: 'https://ontology.graphmetrix.com/node/',
    event: 'http://purl.org/NET/c4dm/event.owl#',
    opmv: 'http://purl.org/net/opmv/ns#',
    prov: 'http://www.w3.org/ns/prov#',
    uri4uri: 'http://uri4uri.net/vocab#',
    posix: 'https://www.w3.org/ns/posix/stat#',
    tl: 'http://purl.org/NET/c4dm/timeline.owl#',
    geo: 'http://www.w3.org/2003/01/geo/wgs84_pos#',
};