version: '1.0'

services:
  timescaledb:
    nameOverride: timescaledb
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - "0.0.0.0:5432:5432/tcp"
    networks:
      xdrop-network:
    environment:
      - POSTGRES_PASSWORD: xDr0p
      - POSTGRES_USER: postgres
    volumes:
      - xdrop_data:/var/lib/postgresql/data
  pgagent:
    depends_on:
      - timescaledb
    image: dpage/pgadmin4:latest 
    restart: always
    entrypoint: /bin/sh -c
                "/tmp/wait-for-it.sh postgres:5432 --timeout=30 &&
                PGPASSWORD='123456' psql -U postgres -h postgres -p 5432 -d test -c 'CREATE EXTENSION IF NOT EXISTS pgagent;' &&
                PGPASSWORD='123456' pgagent -f hostaddr=postgres dbname=test user=postgres port=5432"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "0.0.0.0:8080:80"
    networks:
      xdrop-network:
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  grafana:
    depends_on:
      - timescaledb
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - timescaledb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
volumes:
  xdrop_data:
    driver: local
  pgadmin_data:
    driver: local
  grafana:
    driver: local
networks: 
  xdrop-network:
    driver: bridge
    external: true